### ISSUE TITLE
Update to arkworks-0.4.0

### ISSUE THREAD

**Issue by imikushin** [EspressoSystems/hyperplonk#125]
arkworks v0.4.0 introduces unbelievable amount of breaking changes, and they are clearly moving on full speed. Any improvements (and bug fixes) are going to build on v0.4.0 and up.

To be able to take advantage of those improvements and fixes, Hyperplonk needs to update its arkworks dependencies to v0.4.0 as soon as possible.

**Comment by imikushin** [comment]
Also, I'm already working on it 😎 
PR soon

**Comment by chancharles92** [comment]
> Also, I'm already working on it 😎
> PR soon
Thank you Ivan!
